api_version: 1
threadsafe: true
runtime: python27

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /.*
  script: transfer.app


libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
